### ISSUE TITLE
Jumble activity not loading on 22.04 based OS

### ISSUE THREAD

**Issue by Ark74** [sugarlabs/jumble-activity#15]
Hello!
I'm testing some activities for the Trisquel 11.0 release, codename Aramo, it is based on 22.04 Jammy.

I'm looking at this behavior when trying to launch jumble.
![jumble](https://user-images.githubusercontent.com/7444518/177431540-57e6433b-1ed3-4bd6-9240-0ff6ba3705ba.png)

Have you seen the same by any chance?
Any log I can share?

**Comment by Ark74** [comment]
here some logs,

```
Fatal Python error: pygame_parachute: (pygame parachute) Segmentation Fault
Python runtime state: initialized

Current thread 0x00007fedaa7c6000 (most recent call first):
  File "/usr/lib/python3/dist-packages/sugar3/activity/activity.py", line 879 in get_preview
  File "/usr/lib/python3/dist-packages/sugar3/activity/activity.py", line 968 in save
  File "/usr/lib/python3/dist-packages/sugar3/activity/activity.py", line 612 in set_active
  File "/usr/lib/python3/dist-packages/gi/_propertyhelper.py", line 401 in obj_set_property
  File "/usr/lib/python3/dist-packages/sugar3/activity/activityservice.py", line 67 in SetActive
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 715 in _message_cb
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 1680 in main
  File "/usr/lib/python3/dist-packages/sugar3/activity/activity.py", line 497 in run_main_loop
  File "/usr/lib/python3/dist-packages/sugar3/activity/activityinstance.py", line 233 in main
  File "/usr/bin/sugar-activity3", line 5 in <module>

Extension modules: _dbus_bindings, _dbus_glib_bindings, gi._gi, cairo._cairo, gi._gi_cairo, pygame.base, pygame.constants, pygame.rect, pygame.rwobject, pygame.surflock, pygame.color, pygame.bufferproxy, pygame.math, pygame.surface, pygame.display, pygame.draw, pygame.event, pygame.imageext, pygame.image, pygame.joystick, pygame.key, pygame.mouse, pygame.time, pygame.mask, pygame.pixelcopy, pygame.transform, pygame.font, pygame.mixer_music, pygame.mixer, pygame.scrap, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg.lapack_lite, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, pygame._freetype (total: 45)
pygame 2.1.2 (SDL 2.0.20, Python 3.10.4)
Hello from the pygame community. https://www.pygame.org/contribute.html
Terminated by signal 6, pid 1933 activity_id 9b4ecbd785c53cb6d4960ecdbfc85c3c18f38609
```

**Comment by quozl** [comment]
Same here.  I tested 6d607f43cab7004780cb2b61d9e4287a2f9ea115 and it failed with an AttributeError on line 17 of load_save.py, 'g' has no attribute 'count'.

**Comment by sparshg** [comment]
Getting same error at 35d66c9 on Ubuntu 22.04 LTS, native sugar, python 3.10
However, activity works on 6d607f4 when switched to python 3.6, pygame 1.9.4, native sugar

<details>
<summary>
Traceback
</summary>

```
pygame 2.1.2 (SDL 2.0.20, Python 3.10.4)
Hello from the pygame community. https://www.pygame.org/contribute.html
1657532094.720473 ERROR dbus.connection: Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 232, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sugar3/datastore/datastore.py", line 61, in __datastore_created_cb
    metadata = _get_data_store().get_properties(object_id, byte_arrays=True)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.ValueError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 715, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python3/dist-packages/carquinyol/datastore.py", line 483, in get_properties
    metadata = self._metadata_store.retrieve(uid)
  File "/usr/lib/python3/dist-packages/carquinyol/metadatastore.py", line 79, in retrieve
    metadata = metadatareader.retrieve(metadata_path, properties)
ValueError: Failed to convert metadata value to bytes

1657532094.725892 ERROR dbus.connection: Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 232, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sugar3/datastore/datastore.py", line 66, in __datastore_updated_cb
    metadata = _get_data_store().get_properties(object_id, byte_arrays=True)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.ValueError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 715, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python3/dist-packages/carquinyol/datastore.py", line 483, in get_properties
    metadata = self._metadata_store.retrieve(uid)
  File "/usr/lib/python3/dist-packages/carquinyol/metadatastore.py", line 79, in retrieve
    metadata = metadatareader.retrieve(metadata_path, properties)
ValueError: Failed to convert metadata value to bytes

Fatal Python error: pygame_parachute: (pygame parachute) Segmentation Fault
Python runtime state: initialized

Current thread 0x00007f8d8b7f91c0 (most recent call first):
  File "/usr/local/lib/python3.10/dist-packages/sugar3/activity/activity.py", line 879 in get_preview
  File "/usr/local/lib/python3.10/dist-packages/sugar3/activity/activity.py", line 968 in save
  File "/usr/local/lib/python3.10/dist-packages/sugar3/activity/activity.py", line 612 in set_active
  File "/usr/lib/python3/dist-packages/gi/_propertyhelper.py", line 401 in obj_set_property
  File "/usr/local/lib/python3.10/dist-packages/sugar3/activity/activityservice.py", line 67 in SetActive
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 715 in _message_cb
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 1680 in main
  File "/usr/local/lib/python3.10/dist-packages/sugar3/activity/activity.py", line 497 in run_main_loop
  File "/usr/local/lib/python3.10/dist-packages/sugar3/activity/activityinstance.py", line 233 in main
  File "/usr/local/bin/sugar-activity3", line 5 in <module>

Extension modules: _dbus_bindings, _dbus_glib_bindings, gi._gi, cairo._cairo, gi._gi_cairo, pygame.base, pygame.constants, pygame.rect, pygame.rwobject, pygame.surflock, pygame.color, pygame.bufferproxy, pygame.math, pygame.surface, pygame.display, pygame.draw, pygame.event, pygame.imageext, pygame.image, pygame.joystick, pygame.key, pygame.mouse, pygame.time, pygame.mask, pygame.pixelcopy, pygame.transform, pygame.font, pygame.mixer_music, pygame.mixer, pygame.scrap, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg.lapack_lite, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, pygame._freetype (total: 45)
[1]    2738 IOT instruction (core dumped)  sugar-activity3 .
```

</details>
